### ISSUE TITLE
Rethink grid

### ISSUE THREAD

**Issue by rdbende** [tukaan/tukaan#17]
## Implement placing by cell name, like you'd do it in css
- [x] Done

In css you can do things like this to place an element by grid cell name:
```css
.some__parent {
  grid-template-areas:
      "label button . ."
      "frame frame other other"
      "button_1 button_1 other other";
}

.some__widget {
  grid-area: other
}
```
This will place the widget in `row: 1`, `column: 2`, and will set the column and rowspan.

So in Tukaan instead of this:
```python
some_widget.layout.grid(row=1, col=2, rowspan=2, colspan=2)
```
you could write this, and cells are already created for the rest of the widgets:
```python
some_parent.layout.grid_cells = [
    ["label", "button", None, None],
    ["frame", "frame", "other", "other"],
    ["button_1", "button_1", "other", "other"],
]
some_widget.layout.grid(cell="other")
```

## Allow to row-, and columnconfigure widgets, by setting size template (like in css)
- [x] Done

### In css
```css
.some__parent {
  grid-template-columns: 1fr 1fr 1fr 3fr;
  grid-template-rows: 0fr 1fr 1fr;
}
```

### In Tkinter
```python
some_parent.columnconfigure(index=0, weight=1)
some_parent.columnconfigure(index=1, weight=1)
some_parent.columnconfigure(index=2, weight=1)
some_parent.columnconfigure(index=3, weight=3)

some_parent.rowconfigure(index=0, weight=0)
some_parent.rowconfigure(index=1, weight=1)
some_parent.rowconfigure(index=2, weight=1)
```

### In Tukaan
```python
some_parent.layout.grid_column_template = (1, 1, 1, 3)
some_parent.layout.grid_row_template = (0, 1, 1)
```
